### ISSUE TITLE
Compile error - Control reaches end of non-void function

### ISSUE THREAD

**Issue by citizenlee** [isovic/graphmap#55]
Ran into the following compile error below:

> src/graphmap/graphmap.cc: In member function ‘std::shared_ptr<is::MinimizerIndex> GraphMap::SetupIndex_(std::shared_ptr<SequenceFile>, const string&, const string&, const ProgramParameters&, int64_t) const’:
src/graphmap/graphmap.cc:215:10: error: cannot bind ‘std::unique_ptr<is::MinimizerIndex>’ lvalue to ‘std::unique_ptr<is::MinimizerIndex>&&’
   return index;
          ^
In file included from /usr/include/c++/4.8.3/memory:82:0,
                 from ./src/sparsehash/dense_hash_map:102,
                 from codebase/gindex/src/minimizer_index/minimizer_index.h:11,
                 from ./src/graphmap/graphmap.h:23,
                 from src/graphmap/graphmap.cc:11:
/usr/include/c++/4.8.3/bits/shared_ptr.h:257:2: error:   initializing argument 1 of ‘std::shared_ptr<_Tp>::shared_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Tp1 = is::MinimizerIndex; _Del = std::default_delete<is::MinimizerIndex>; _Tp = is::MinimizerIndex]’
  shared_ptr(std::unique_ptr<_Tp1, _Del>&& __r)
  ^
src/graphmap/graphmap.cc:216:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: some warnings being treated as errors
make: *** [obj_linux/src/graphmap/graphmap.o] Error 1

**Comment by isovic** [comment]
Hmm strange...can you try using a newer compiler and letting me know how it works?
For me it works well on g++ 6.2 on several machines.

Best regards,
Ivan.

**Comment by citizenlee** [comment]
Will try this on a different computer. The above was run on an Amazon AMI.

**Comment by deathmantim** [comment]
I am having the same problem with g++ version 4.8.4 on ubuntu 14.04

**Comment by citizenlee** [comment]
Using brew to install gcc 6.1 without multilib (for openmp), I get the following compilation failure:

Makefile:100: "*** WARNING g++ minor version <7 ***"
mkdir -p obj_linux/codebase/gindex/src/minimizer_index/
g++ -static-libgcc -static-libstdc++ -D__cplusplus=201103L -I"./src/" -I"/usr/include/" -I"codebase/seqlib/src/libs/seqan-library-2.0.1/include" -I"codebase/seqlib/src/libs/libdivsufsort-2.0.1-64bit/" -Icodebase/argumentparser/src -Icodebase/gindex/src -Icodebase/seqlib/src -DRELEASE_VERSION -O3 -fdata-sections -ffunction-sections -c -fmessage-length=0 -ffreestanding -fopenmp -m64 -std=c++11 -Werror=return-type -pthread  -o obj_linux/codebase/gindex/src/minimizer_index/minimizer_index.o codebase/gindex/src/minimizer_index/minimizer_index.cc
codebase/gindex/src/minimizer_index/minimizer_index.cc:2:26: error: expected constructor, destructor, or type conversion before '.' token
  * index_gapped_minimizer.cc
                          ^
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:57:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:59,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/utility:70,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/algorithm:60,
                 from ./src/sparsehash/dense_hash_map:100,
                 from codebase/gindex/src/minimizer_index/minimizer_index.h:11,
                 from codebase/gindex/src/minimizer_index/minimizer_index.cc:8:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:352:31: error: 'std::size_t' has not been declared
   template<typename _Tp, std::size_t _Size>
                               ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:353:25: error: '_Size' was not declared in this scope
     struct is_array<_Tp[_Size]>
                         ^~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:353:31: error: template argument 1 is invalid
     struct is_array<_Tp[_Size]>
                               ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:551:37: error: 'nullptr_t' is not a member of 'std'
     struct __is_null_pointer_helper<std::nullptr_t>
                                     ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:551:37: error: 'nullptr_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:551:51: error: template argument 1 is invalid
     struct __is_null_pointer_helper<std::nullptr_t>
                                                   ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1467:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t, __alignof__(_Tp)> { };
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1467:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1467:61: error: template argument 1 is invalid
     : public integral_constant<std::size_t, __alignof__(_Tp)> { };
                                                             ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1467:61: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1472:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t, 0> { };
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1472:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1472:46: error: template argument 1 is invalid
     : public integral_constant<std::size_t, 0> { };
                                              ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1472:46: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1474:31: error: 'std::size_t' has not been declared
   template<typename _Tp, std::size_t _Size>
                               ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1475:21: error: '_Size' was not declared in this scope
     struct rank<_Tp[_Size]>
                     ^~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1475:27: error: template argument 1 is invalid
     struct rank<_Tp[_Size]>
                           ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1476:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t, 1 + rank<_Tp>::value> { };
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1476:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1476:65: error: template argument 1 is invalid
     : public integral_constant<std::size_t, 1 + rank<_Tp>::value> { };
                                                                 ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1476:65: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1480:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t, 1 + rank<_Tp>::value> { };
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1480:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1480:65: error: template argument 1 is invalid
     : public integral_constant<std::size_t, 1 + rank<_Tp>::value> { };
                                                                 ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1480:65: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1485:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t, 0> { };
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1485:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1485:46: error: template argument 1 is invalid
     : public integral_constant<std::size_t, 0> { };
                                              ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1485:46: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1487:47: error: 'std::size_t' has not been declared
   template<typename _Tp, unsigned _Uint, std::size_t _Size>
                                               ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1488:23: error: '_Size' was not declared in this scope
     struct extent<_Tp[_Size], _Uint>
                       ^~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1488:36: error: template argument 1 is invalid
     struct extent<_Tp[_Size], _Uint>
                                    ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1489:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t,
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1489:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1490:24: error: '_Size' was not declared in this scope
           _Uint == 0 ? _Size : extent<_Tp,
                        ^~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1491:28: error: template argument 1 is invalid
           _Uint - 1>::value>
                            ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1491:28: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1496:32: error: 'size_t' is not a member of 'std'
     : public integral_constant<std::size_t,
                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1496:32: error: 'size_t' is not a member of 'std'
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1498:31: error: template argument 1 is invalid
              _Uint - 1>::value>
                               ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1498:31: note: invalid template non-type parameter
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1947:31: error: 'std::size_t' has not been declared
   template<typename _Tp, std::size_t _Size>
                               ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1948:30: error: '_Size' was not declared in this scope
     struct remove_extent<_Tp[_Size]>
                              ^~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1948:36: error: template argument 1 is invalid
     struct remove_extent<_Tp[_Size]>
                                    ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1960:31: error: 'std::size_t' has not been declared
   template<typename _Tp, std::size_t _Size>
                               ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1961:35: error: '_Size' was not declared in this scope
     struct remove_all_extents<_Tp[_Size]>
                                   ^~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:1961:41: error: template argument 1 is invalid
     struct remove_all_extents<_Tp[_Size]>
                                         ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2019:17: error: 'std::size_t' has not been declared
   template<std::size_t _Len>
                 ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2024:23: error: '_Len' was not declared in this scope
  unsigned char __data[_Len];
                       ^~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2039:17: error: 'std::size_t' has not been declared
   template<std::size_t _Len, std::size_t _Align =
                 ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2039:35: error: 'std::size_t' has not been declared
   template<std::size_t _Len, std::size_t _Align =
                                   ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2040:48: error: '_Len' was not declared in this scope
     __alignof__(typename __aligned_storage_msa<_Len>::__type)>
                                                ^~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2040:52: error: template argument 1 is invalid
     __alignof__(typename __aligned_storage_msa<_Len>::__type)>
                                                    ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2045:23: error: '_Len' was not declared in this scope
  unsigned char __data[_Len];
                       ^~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2046:37: error: '_Align' was not declared in this scope
  struct __attribute__((__aligned__((_Align)))) { } __align;
                                     ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2053:20: error: 'size_t' does not name a type
       static const size_t _S_alignment = 0;
                    ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2054:20: error: 'size_t' does not name a type
       static const size_t _S_size = 0;
                    ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2060:20: error: 'size_t' does not name a type
       static const size_t _S_alignment =
                    ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2063:20: error: 'size_t' does not name a type
       static const size_t _S_size =
                    ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2078:13: error: 'size_t' has not been declared
   template <size_t _Len, typename... _Types>
             ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2085:20: error: 'size_t' does not name a type
       static const size_t _S_len = _Len > __strictest::_S_size
                    ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2089:20: error: 'size_t' does not name a type
       static const size_t alignment_value = __strictest::_S_alignment;
                    ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2091:40: error: '_S_len' was not declared in this scope
       typedef typename aligned_storage<_S_len, alignment_value>::type type;
                                        ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2091:48: error: 'alignment_value' was not declared in this scope
       typedef typename aligned_storage<_S_len, alignment_value>::type type;
                                                ^~~~~~~~~~~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2091:63: error: template argument 1 is invalid
       typedef typename aligned_storage<_S_len, alignment_value>::type type;
                                                               ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2091:63: error: template argument 2 is invalid
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2094:13: error: 'size_t' has not been declared
   template <size_t _Len, typename... _Types>
             ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2095:11: error: 'size_t' does not name a type
     const size_t aligned_union<_Len, _Types...>::alignment_value;
           ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2604:26: error: 'size_t' has not been declared
   template<typename _Tp, size_t _Nm>
                          ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:21: error: '_Nm' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                     ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:24: error: 'std::swap' declared as an 'inline' variable
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                        ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:24: error: 'template<class _Tp, <declaration error> > typename std::enable_if<std::__is_swappable<_Tp>::value>::type std::swap' conflicts with a previous declaration
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2600:5: note: previous declaration 'typename std::enable_if<std::__and_<std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&)'
     swap(_Tp&, _Tp&)
     ^~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:16: error: '__a' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:21: error: '_Nm' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                     ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:33: error: '__b' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                                 ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2607:38: error: '_Nm' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                                      ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/type_traits:2608:5: error: expected ';' before 'noexcept'
     noexcept(__is_nothrow_swappable<_Tp>::value);
     ^~~~~~~~
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:59:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/utility:70,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/algorithm:60,
                 from ./src/sparsehash/dense_hash_map:100,
                 from codebase/gindex/src/minimizer_index/minimizer_index.h:11,
                 from codebase/gindex/src/minimizer_index/minimizer_index.cc:8:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:198:26: error: 'size_t' has not been declared
   template<typename _Tp, size_t _Nm>
                          ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:21: error: '_Nm' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                     ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:24: error: 'std::swap' declared as an 'inline' variable
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                        ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:24: error: 'template<class _Tp, <declaration error> > typename std::enable_if<std::__is_swappable<_Tp>::value>::type std::swap' conflicts with a previous declaration
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:179:5: note: previous declaration 'typename std::enable_if<std::__and_<std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&)'
     swap(_Tp& __a, _Tp& __b)
     ^~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:16: error: '__a' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:21: error: '_Nm' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                     ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:33: error: '__b' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                                 ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:202:38: error: '_Nm' was not declared in this scope
     swap(_Tp (&__a)[_Nm], _Tp (&__b)[_Nm])
                                      ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/move.h:203:5: error: expected ';' before 'noexcept'
     noexcept(__is_nothrow_swappable<_Tp>::value)
     ^~~~~~~~
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/utility:70:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/algorithm:60,
                 from ./src/sparsehash/dense_hash_map:100,
                 from codebase/gindex/src/minimizer_index/minimizer_index.h:11,
                 from codebase/gindex/src/minimizer_index/minimizer_index.cc:8:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:85:17: error: 'std::size_t' has not been declared
   template<std::size_t...>
                 ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:353:41: error: 'std::size_t' has not been declared
       template<typename... _Args1, std::size_t... _Indexes1,
                                         ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:354:41: error: 'std::size_t' has not been declared
                typename... _Args2, std::size_t... _Indexes2>
                                         ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:356:27: error: '_Indexes1' was not declared in this scope
              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
                           ^~~~~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:356:36: error: expected parameter pack before '...'
              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
                                    ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:356:39: error: template argument 1 is invalid
              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
                                       ^
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:356:55: error: '_Indexes2' was not declared in this scope
              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
                                                       ^~~~~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:356:64: error: expected parameter pack before '...'
              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
                                                                ^~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/bits/stl_pair.h:356:67: error: template argument 1 is invalid
              _Index_tuple<_Indexes1...>, _Index_tuple<_Indexes2...>);
                                                                   ^
In file included from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/utility:76:0,
                 from /usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/algorithm:60,
                 from ./src/sparsehash/dense_hash_map:100,
                 from codebase/gindex/src/minimizer_index/minimizer_index.h:11,
                 from codebase/gindex/src/minimizer_index/minimizer_index.cc:8:
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/initializer_list:53:15: error: 'size_t' does not name a type
       typedef size_t   size_type;
               ^~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/initializer_list:59:7: error: 'size_type' does not name a type
       size_type   _M_len;
       ^~~~~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/initializer_list:62:54: error: 'size_type' has not been declared
       constexpr initializer_list(const_iterator __a, size_type __l)
                                                      ^~~~~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/initializer_list:70:17: error: 'size_type' does not name a type
       constexpr size_type
                 ^~~~~~~~~
/usr/local/Cellar/gcc/6.1.0/include/c++/6.1.0/initializer_list:47:11: fatal error: definition of std::initializer_list does not match #include <initializer_list>
     class initializer_list
           ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [obj_linux/codebase/gindex/src/minimizer_index/minimizer_index.o] Error 1

**Comment by citizenlee** [comment]
I was able to compile on Amazon Ubuntu 16.04 (ami-f4cc1de2) after installing gcc/g++/zlib1g-dev

**Comment by isovic** [comment]
Hi all,
thank you for reporting back!

It seems there was an important change between C++11 and C++14 standards: http://stackoverflow.com/questions/35906268/returning-local-unique-ptr-as-a-shared-ptr .

In the commit you tested I implicitly converted from std::unique_ptr to std::shared_ptr, which older versions of g++ could not handle.

I fixed this in the latest commit (about 15mins ago) and tested on g++ 4.8.4 and it seems to work.

Would it be possible for any of you to verify the fix?

Thank you,
Best regards,
Ivan.

**Comment by citizenlee** [comment]
Latest commit did compile for me with g++ 4.8.3 on Amazon Linux AMI. Running a clang error - unsupported option '-fopenmp' on my mac - will work on this more.

**Comment by isovic** [comment]
Hi Henry!
Thank you for testing and reporting back!
Glad to hear it works on older compilers now.
As for clang, from what I hear (I'm not a Mac user) it does not have a support for OpenMP for some reason...

Thanks again!
Best regards,
Ivan.

**Comment by deathmantim** [comment]
Hey isovic,
I was also able to compile on g++ 4 on ubuntu 14.04.
Thanks for the replies!
Tim

**Comment by isovic** [comment]
Hey Tim!
Great to hear - thanks for reporting!

Best regards,
Ivan.
